# Generated by Django 4.2.5 on 2023-11-14 23:17

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_alter_autor_options_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(default='1980-01-01', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='idade',
            field=models.PositiveSmallIntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='nome', chained_model_field='nome', on_delete=django.db.models.deletion.CASCADE, to='noticia.autor'),
        ),
    ]
