# Generated by Django 4.2.7 on 2023-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_alter_autor_options_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(default='1980-01-01', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='idade',
            field=models.PositiveSmallIntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
