# Generated by Django 4.2.5 on 2023-11-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0006_alter_noticia_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'permissions': [('pode_publicar', 'Pode publicar uma noticia')], 'verbose_name': 'Escritor', 'verbose_name_plural': 'Escritores'},
        ),
    ]
