# Generated by Django 4.2.5 on 2023-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0008_autor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
    ]
